version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: .env
    depends_on:
      - mongo

  mongo:
    container_name: database
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27018:27017"

volumes:
  data:
  frontend:
  backend:
