version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: database
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes:
  frontend_node_modules:
  backend_node_modules:
  data:
